package almoxerifado;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.util.Properties;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 * Tela de configuração da conexão
 * @author Welison
 */
public class Configuracao extends JFrame {
    
    private final Properties params;
    private final Login login;
    
    /**
     * Creates new form de configuração da conexão
     * @param login the Login JFrame
     */
    public Configuracao(Login login) {
        
       this.login = login;
       timerTest();
        
        initComponents();
        this.params = new Properties();
     
    }
    
    /**
     * retorna a instância atual
     * @return a instância atual do JFrame
     */
    private JFrame getInstance() {
        return this;
    }
    
    
    private Timer t;
    /**
     * Apos algum tempo esconde a tela de login
     */
    private void timerTest() {
        
        t = new Timer(250, (ActionEvent e) -> {
            login.setVisible(false);
            t.stop();
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBg = new javax.swing.JPanel();
        ltitulo = new javax.swing.JLabel();
        lhost = new javax.swing.JLabel();
        fhost = new javax.swing.JTextField();
        lsenha = new javax.swing.JLabel();
        bentrar = new javax.swing.JButton();
        fsenha = new javax.swing.JPasswordField();
        luser = new javax.swing.JLabel();
        fuser = new javax.swing.JTextField();
        lhost1 = new javax.swing.JLabel();
        fdatabase = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(37, 38, 39));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBg.setPreferredSize(new java.awt.Dimension(400, 300));
        jBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ltitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ltitulo.setText("Dados da conexão");
        jBg.add(ltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        lhost.setText("Host");
        jBg.add(lhost, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 20));
        jBg.add(fhost, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 240, -1));

        lsenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lsenha.setText("Senha");
        jBg.add(lsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 20));

        bentrar.setText("Salvar");
        bentrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bentrarActionPerformed(evt);
            }
        });
        jBg.add(bentrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 70, 30));
        jBg.add(fsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 240, -1));

        luser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        luser.setText("Usuário");
        jBg.add(luser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 20));
        jBg.add(fuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 240, -1));

        lhost1.setText("Database");
        jBg.add(lhost1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 20));
        jBg.add(fdatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 240, -1));

        getContentPane().add(jBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Escuta o evento de click do botão de login
     * @param evt o ActionEvent
     */
    private void bentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bentrarActionPerformed
        

        // validação
        boolean isValid = true;
        //if (! Validator.validaCampo(fhost, ehost, 1000)) isValid = false;
        //if (! Validator.validaCampo(fuser, euser, 1000)) isValid = false;
        //if (! Validator.validaCampo(fsenha, epassword, 1000)) isValid = false;
        if (isValid) {
            ConnectionFactory conTest = new ConnectionFactory();
            String password = new String(fsenha.getPassword()).trim();
            String host = fhost.getText().trim();
            String user = fuser.getText().trim();
            String database = fdatabase.getText().trim();
            
            // testa a conexão
            if (conTest.testConexao(host, database, user, password)) {
                ConfigGenerator configGenerator = new ConfigGenerator();
                configGenerator.createConfig(host, database, user, password);
                
                // esconde a janela corrente e mostra a de login
                this.dispose();
                this.login.setVisible(true);
                this.login.buildPage();
            } else {
                Toolkit.getDefaultToolkit().beep();
                JOptionPane.showMessageDialog(null, "Conexão mal sucedida.");
            }
        } else {
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_bentrarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bentrar;
    private javax.swing.JTextField fdatabase;
    private javax.swing.JTextField fhost;
    private javax.swing.JPasswordField fsenha;
    private javax.swing.JTextField fuser;
    private javax.swing.JPanel jBg;
    private javax.swing.JLabel lhost;
    private javax.swing.JLabel lhost1;
    private javax.swing.JLabel lsenha;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JLabel luser;
    // End of variables declaration//GEN-END:variables

}
